name: Azure VM Deployment

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host:  104.211.116.221 # Azure VM host/IP address
          username: testvm  # Azure VM username
          key: testvm@12345  # SSH private key stored as GitHub secret
          script: |
            sudo cp default1.html /var/www/html/default1.html
