name: Azure VM Deployment

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to vm
        uses: appleboy/ssh-action@master
        with: 
             host: ${{ secrets.TESTVM_IP }}
             username: ${{ secrets.TESTVM_USERNAME }}
             #password: ${{ secrets.TESTVM_PASSWORD }}
             key: ${{ secrets.TESTVM_SSH_KEY }}  


      - name: Deploy code to vm  
        run: scp -i <(echo "${{ secrets.TESTVM_SSH_KEY }}") default1.html ${{ secrets.TESTVM_USERNAME }}@${{ secrets.TESTVM_IP }}:/var/www/html/default1.html
