name: Azure VM Deployment

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to vm
        uses: appleboy/ssh-action@master
        with: 
             host: ${{ secrets.TESTVM_IP }}
             username: ${{ secrets.TESTVM_USERNAME }}
             #password: ${{ secrets.TESTVM_PASSWORD }}
             key: ${{ secrets.TESTVM_SSH_KEY }}  
             script: |
              mkdir /home/$(whoami)/deployment_git/ ; git clone -v https://github.com/deepak-njr/testvm.git /home/$(whoami)/deployment_git/ ; sudo rm -rf /var/www/html/* ; sudo cp -r /home/$(whoami)/deployment_git/* /var/www/html/ ; rm -rf /home/$(whoami)/deployment_git/ ; sudo systemctl restart nginx


