name: Azure VM Deployment

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure VM
        #uses: appleboy/ssh-action@master
          #host: 104.211.116.221
          #username: testvm  # Azure VM username
          #password: testvm@12345  # Azure VM password stored as GitHub secret
        run: scp -o StrictHostKeyChecking=no default1.html testvm@104.211.116.221:/var/www/html/default1.html
