name: View Root Directory

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  view_root_directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List contents of root directory
        run: ls -la
