name: Azure VM Deployment

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.testvm_ip }}  # Azure VM host/IP address
          username: ${{ secrets.testvm_username }}  # Azure VM username
          key: ${{ secrets.testvm_password }}  # SSH private key stored as GitHub secret
          script: |
            sudo cp default1.html /var/www/html/default1.html
