name: Azure VM Deployment

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to vm
        uses: appleboy/ssh-action@master
        with: 
             host: 104.211.116.221
             username: testvm
             password: testvm@12345
             key: ${{ secrets.TESTVM_SSH_KEY }}  


      - name: Deploy code to vm  
        run: scp -o StrictHostKeyChecking=no default1.html testvm@104.211.116.221:/var/www/html/default1.html
